import type { NodeType, Outcome } from '../model/tree'
import {
  branchLabel,
  detachChild,
  displayName,
  setChild,
  TreeNode,
} from '../model/tree'
import type { ConditionalRow } from '../model/tree'
import {
  addOutcomeToGroup,
  adoptGroupProbabilities,
  mirrorLinkedInstances,
  createLinkedNode,
  groupSiblings,
  hasConditionalTable,
  removeOutcomeFromGroup,
  renameOutcomeInGroup,
  renameVariable,
  setNodeTypeInGroup,
  syncProbabilitiesFromNode,
  unlinkNode,
} from '../model/variable'
import { backwardFill } from '../model/backwardFill'
import { resolveProbability } from '../model/conditionalProbability'
import { reorderAdjacentLevels, reverseTreeWithBayes } from '../model/bayesReversal'
import { deserializeDocument, documentFilename, documentToJson } from '../model/document'
import type { DecisionDocument } from '../model/document'
import { certaintyEquivalent } from '../model/expectedUtility'
import { calculateExpectedValue } from '../model/expectedValue'
import { traceNode, traceTerminalUtility } from '../model/calculationTrace'
import {
  applyInverseUtility,
  applyUtility,
  defaultUtilityFunction,
  gammaFromIndifference,
  gammaFromReferenceAmount,
  riskOddsFromGamma,
  UtilityDomainError,
} from '../model/utility'
import type { UtilityFunction, UtilityType } from '../model/utility'
import { applyViewTransform, fmt, renderTree } from '../render/renderTree'
import { exportTreePng } from '../render/pngExport'
import type { DisplayMode, ViewTransform } from '../render/renderTree'

export interface AppState {
  root: TreeNode | null
  /** The right (clairvoyance) tree. Null until the first flip. Generated by
   * Bayes-reversal from the left tree, then FULLY EDITABLE and independent — no
   * further sync with the left. Persisted in the document (see document.ts). */
  rightRoot: TreeNode | null
  /** True once the right tree has been manually edited since its last
   * generation — drives the "edited since flip" deviation indicator and marks
   * VOC as a free comparison rather than strict clairvoyance. */
  rightEdited: boolean
  /** Last flip-generation error (unflippable structure), shown in the right
   * pane. Null when the last generation succeeded. */
  flipError: string | null
  selected: TreeNode | null
  message: string
  /** Split mode: shows the right (clairvoyance) tree beside the left. Entering
   * split regenerates the right tree from the left; both are then editable. */
  split: boolean
  /** 'ev' = risk-neutral expected value; 'eu' = certainty equivalent under
   * `utilityFn` (risk-adjusted). */
  displayMode: DisplayMode
  utilityFn: UtilityFunction
  view: ViewTransform
  viewRight: ViewTransform
  idCounter: number
  /** True when the tree/settings changed since the last save or load — used
   * to confirm before a load would discard unsaved work. */
  dirty: boolean
}

/** One undo/redo history entry: the full document as JSON (deep clone via the
 * tested serialize round-trip — now includes BOTH trees, the deviation flag and
 * split mode) plus the selected node id (which may live in either tree). */
interface Snapshot {
  json: string
  selectedId: string | null
}

export interface AppApi {
  createRoot(type: NodeType, label: string): TreeNode
  addOutcomeTo(node: TreeNode, label: string, probability?: number, value?: number): Outcome
  attachChild(node: TreeNode, edge: Outcome, type: NodeType, label: string): TreeNode
  toggleType(node: TreeNode): void
  renameNode(node: TreeNode, label: string): void
  unlinkVariable(node: TreeNode): void
  renameOutcomeOn(node: TreeNode, edge: Outcome, newLabel: string): void
  removeOutcomeFrom(node: TreeNode, edge: Outcome): void
  /** Swaps two adjacent LEVELS of the tree that `panelRoot` roots (the level at
   * `upperDepth` and the one below it), restructuring that tree in place. Used
   * by the pill bar's drag-and-drop. Throws `FlipError` if the swap is invalid
   * (conditional table / unlink boundary / not level-consistent). */
  reorderLevels(panelRoot: TreeNode, upperDepth: number): void
  setProbability(edge: Outcome, probability: number): void
  setValue(edge: Outcome, value: number | undefined): void
  setConditionalTable(node: TreeNode, rows: ConditionalRow[]): void
  deleteNode(node: TreeNode): void
  applyBackwardFill(node: TreeNode, edge: Outcome, targetProbability: number): void
  exportDocument(): string
  loadDocument(text: string, opts?: { skipConfirm?: boolean }): boolean
  toggleSplit(): void
  undo(): void
  redo(): void
  canUndo(): boolean
  canRedo(): boolean
  setDisplayMode(mode: DisplayMode): void
  setUtilityType(type: UtilityType): void
  setUtilityParameter(parameter: number): void
  selectNode(node: TreeNode | null): void
  render(): void
}

export interface App {
  state: AppState
  api: AppApi
}

/** Rounds a set of target probabilities to a clean 6-significant-figure display
 * while guaranteeing the set sums to exactly 1. Every value but the last is
 * rounded normally; the LAST outcome absorbs the rounding residual. This keeps
 * repeating decimals — thirds (0.333333 / 0.333333 / 0.333334), sixths, etc. —
 * from tripping the Σ≠1 validation (tolerance 1e-6), where three bare 0.333333
 * would sum to 0.999999 and fail. `targets` should already sum to ~1. */
export function distributeSumToOne(targets: number[]): number[] {
  const n = targets.length
  if (n === 0) return []
  const out = targets.map((t) => parseFloat(t.toPrecision(6)))
  const headSum = out.slice(0, n - 1).reduce((s, v) => s + v, 0)
  out[n - 1] = parseFloat((1 - headSum).toPrecision(6))
  return out
}

/** `confirmFn` is injectable so tests can run destructive flows headlessly. */
export function createApp(
  container: HTMLElement,
  options: { confirmFn?: (message: string) => boolean } = {},
): App {
  const confirmFn = options.confirmFn ?? ((m: string) => window.confirm(m))

  const state: AppState = {
    root: null,
    rightRoot: null,
    rightEdited: false,
    flipError: null,
    selected: null,
    message: '',
    split: false,
    displayMode: 'ev',
    // Default to exponential CARA when EU mode is first opened — a standard,
    // visibly risk-averse curve, so switching to EU actually shows CE < EV
    // rather than the linear no-op.
    utilityFn: defaultUtilityFunction('exponential'),
    view: { scale: 1, x: 0, y: 0 },
    viewRight: { scale: 1, x: 0, y: 0 },
    idCounter: 0,
    dirty: false,
  }

  // ── Static shell (built once — listeners never accumulate) ──
  container.innerHTML = ''
  container.className = 'app'

  const topbar = document.createElement('header')
  topbar.className = 'topbar'
  const title = document.createElement('span')
  title.className = 'app-title'
  title.textContent = 'DecisionAnalysis'
  const addBtn = document.createElement('button')
  addBtn.id = 'add-node'
  addBtn.textContent = 'Lägg till nod'
  const flipBtn = document.createElement('button')
  flipBtn.id = 'flip'
  flipBtn.textContent = '⇄ Flip'
  flipBtn.title =
    'Visar trädet omvänt (alla slumputfall kända innan besluten) bredvid ditt ' +
    'träd och räknar ut VOC — värdet av klarsyn. Klicka igen för att stänga.'
  const undoBtn = document.createElement('button')
  undoBtn.id = 'undo'
  undoBtn.textContent = '↶'
  undoBtn.title = 'Ångra (Ctrl+Z)'
  const redoBtn = document.createElement('button')
  redoBtn.id = 'redo'
  redoBtn.textContent = '↷'
  redoBtn.title = 'Gör om (Ctrl+Shift+Z)'
  const modeBtn = document.createElement('button')
  modeBtn.id = 'mode-toggle'
  const saveBtn = document.createElement('button')
  saveBtn.id = 'save'
  saveBtn.textContent = '💾 Spara'
  const pngBtn = document.createElement('button')
  pngBtn.id = 'save-png'
  pngBtn.textContent = '🖼 PNG'
  pngBtn.title = 'Spara trädet som PNG-bild (transparent bakgrund)'
  const loadBtn = document.createElement('button')
  loadBtn.id = 'load'
  loadBtn.textContent = '📂 Ladda'
  const fileInput = document.createElement('input')
  fileInput.type = 'file'
  fileInput.accept = 'application/json,.json'
  fileInput.style.display = 'none'
  topbar.append(title, addBtn, flipBtn, undoBtn, redoBtn, modeBtn, saveBtn, pngBtn, loadBtn, fileInput)

  const messageStrip = document.createElement('div')
  messageStrip.className = 'message-strip'
  messageStrip.style.display = 'none'

  // ── Utility-function config bar, shown only in EU mode ──
  const utilityBar = document.createElement('div')
  utilityBar.className = 'utility-bar'
  utilityBar.style.display = 'none'
  const utilityLabel = document.createElement('span')
  utilityLabel.textContent = 'Nyttofunktion:'
  const utilityTypeSelect = document.createElement('select')
  utilityTypeSelect.id = 'utility-type'
  for (const [value, label] of [
    ['linear', 'Linjär (riskneutral)'],
    ['exponential', 'Exponentiell'],
  ] as const) {
    const opt = document.createElement('option')
    opt.value = value
    opt.textContent = label
    utilityTypeSelect.appendChild(opt)
  }
  // γ fine-tune input (exponential only) + elicitation launcher.
  const paramLabel = document.createElement('label')
  paramLabel.className = 'utility-param'
  const paramLabelText = document.createElement('span')
  paramLabelText.textContent = 'γ'
  const paramInput = document.createElement('input')
  paramInput.id = 'utility-parameter'
  paramInput.type = 'text'
  paramInput.inputMode = 'decimal'
  paramLabel.append(paramLabelText, paramInput)
  const elicitBtn = document.createElement('button')
  elicitBtn.id = 'elicit'
  elicitBtn.textContent = 'Ställ in riskattityd…'
  const riskReadout = document.createElement('span')
  riskReadout.className = 'risk-readout'
  utilityBar.append(utilityLabel, utilityTypeSelect, paramLabel, elicitBtn, riskReadout)

  const utilityErrorEl = document.createElement('div')
  utilityErrorEl.className = 'utility-error'
  utilityErrorEl.style.display = 'none'

  const vocBar = document.createElement('div')
  vocBar.className = 'voc-bar'
  vocBar.style.display = 'none'

  // One-line, always-visible explanation of what the VOC number means, so a
  // first-time user doesn't have to know the abbreviation. Shown only in split.
  const vocHint = document.createElement('div')
  vocHint.className = 'voc-hint'
  vocHint.style.display = 'none'
  vocHint.textContent =
    'VOC = värdet av klarsyn: hur mycket det förväntade värdet (EV) ökar om du ' +
    'får veta alla slumputfall innan du fattar besluten. Höger träd visar det ' +
    'omvända beslutsläget som VOC bygger på.'

  // Calculation-trace bar: shows the arithmetic behind the selected node's
  // value. Visible only while a node is selected.
  const traceBar = document.createElement('div')
  traceBar.className = 'trace-bar'
  traceBar.style.display = 'none'

  const workspace = document.createElement('div')
  workspace.className = 'workspace'

  // Left pane = its own pill sequence bar docked on top of the canvas.
  const leftPane = document.createElement('div')
  leftPane.className = 'pane left-pane'
  const leftPillBar = document.createElement('div')
  leftPillBar.className = 'pill-bar'
  const canvasHost = document.createElement('div')
  canvasHost.className = 'canvas-host'
  leftPane.append(leftPillBar, canvasHost)

  const rightPane = document.createElement('div')
  rightPane.className = 'right-pane pane'
  rightPane.style.display = 'none'
  const rightHeader = document.createElement('div')
  rightHeader.className = 'pane-header'
  const rightCaption = document.createElement('div')
  rightCaption.className = 'pane-caption'
  rightCaption.textContent = 'Omvänt träd (klarsyn) — redigerbart'
  // Deviation indicator: shown only once the right tree has been hand-edited
  // since its last generation, so the user knows VOC is now a free comparison.
  const rightDeviation = document.createElement('span')
  rightDeviation.className = 'deviation-badge'
  rightDeviation.style.display = 'none'
  rightDeviation.textContent = '✎ redigerad sedan Sammanfoga'
  rightDeviation.title =
    'Höger träd har redigerats manuellt sedan det genererades. VOC är nu en ' +
    'fri jämförelse (|EV vänster − EV höger|), inte en strikt klarsynsvärdering.'
  rightHeader.append(rightCaption, rightDeviation)
  const rightPillBar = document.createElement('div')
  rightPillBar.className = 'pill-bar'
  const rightHost = document.createElement('div')
  rightHost.className = 'canvas-host canvas-right'
  const flipErrorEl = document.createElement('div')
  flipErrorEl.className = 'flip-error'
  flipErrorEl.style.display = 'none'
  rightPane.append(rightHeader, rightPillBar, rightHost, flipErrorEl)

  workspace.append(leftPane, rightPane)

  const menuLayer = document.createElement('div')
  menuLayer.className = 'menu-layer'

  const dialogLayer = document.createElement('div')
  dialogLayer.className = 'dialog-layer'

  container.append(
    topbar,
    messageStrip,
    utilityBar,
    utilityErrorEl,
    vocBar,
    vocHint,
    traceBar,
    workspace,
    menuLayer,
    dialogLayer,
  )

  let svg: SVGSVGElement | null = null
  let svgRight: SVGSVGElement | null = null

  // ── Zoom & pan, scoped to each canvas only. The view object is mutated
  //    in place so both hosts keep a stable reference across renders. ──
  const wireNav = (
    host: HTMLElement,
    view: ViewTransform,
    getSvg: () => SVGSVGElement | null,
  ): void => {
    host.addEventListener(
      'wheel',
      (e) => {
        e.preventDefault()
        const factor = e.deltaY < 0 ? 1.1 : 1 / 1.1
        const newScale = Math.min(3, Math.max(0.2, view.scale * factor))
        const rect = host.getBoundingClientRect()
        const mx = e.clientX - rect.left
        const my = e.clientY - rect.top
        view.x = mx - ((mx - view.x) / view.scale) * newScale
        view.y = my - ((my - view.y) / view.scale) * newScale
        view.scale = newScale
        const s = getSvg()
        if (s) applyViewTransform(s, view)
      },
      { passive: false },
    )

    let panStart: { mx: number; my: number; vx: number; vy: number } | null = null
    host.addEventListener('pointerdown', (e) => {
      if ((e.target as Element).closest('g.node, g.leaf')) return
      panStart = { mx: e.clientX, my: e.clientY, vx: view.x, vy: view.y }
    })
    host.addEventListener('pointermove', (e) => {
      if (!panStart) return
      view.x = panStart.vx + e.clientX - panStart.mx
      view.y = panStart.vy + e.clientY - panStart.my
      const s = getSvg()
      if (s) applyViewTransform(s, view)
    })
    host.addEventListener('pointerup', () => {
      panStart = null
    })
    host.addEventListener('dblclick', (e) => {
      if ((e.target as Element).closest('g.node, g.leaf')) return
      view.scale = 1
      view.x = 0
      view.y = 0
      const s = getSvg()
      if (s) applyViewTransform(s, view)
    })
  }
  wireNav(canvasHost, state.view, () => svg)
  wireNav(rightHost, state.viewRight, () => svgRight)

  const nextId = (): string => `n${++state.idCounter}`

  const setMessage = (text: string): void => {
    state.message = text
    messageStrip.textContent = text
    messageStrip.style.display = text ? '' : 'none'
  }

  // ── Undo/redo history (snapshot-based) ──
  // `history[cursor]` is always the current committed state; earlier entries
  // are undo targets, later ones redo targets. A committed mutation sets
  // `pendingCommit`, and the tail of render() snapshots — so multi-node effects
  // (auto-fill, linked-group sync) that all finish before the single render()
  // collapse into ONE undo step. `restoring` suppresses that while we replay.
  const HISTORY_CAP = 100
  const history: Snapshot[] = []
  let cursor = -1
  let pendingCommit = false
  let restoring = false

  const markDirty = (): void => {
    state.dirty = true
    if (!restoring) pendingCommit = true
  }

  const guarded = (fn: () => void): void => {
    try {
      fn()
    } catch (e) {
      setMessage(e instanceof Error ? e.message : String(e))
    }
  }

  const incomingEdge = (node: TreeNode): { parent: TreeNode; edge: Outcome } | null => {
    if (!node.parent) return null
    const edge = node.parent.outcomes.find((o) => o.child === node)
    return edge ? { parent: node.parent, edge } : null
  }

  /** History token set for the path root -> `node` (the outcome labels taken
   * to reach it), so conditional probabilities resolve correctly for the
   * node's calculation trace. */
  const historyFor = (node: TreeNode): Set<string> => {
    const tokens: string[] = []
    let current = node
    for (let inc = incomingEdge(current); inc; inc = incomingEdge(current)) {
      tokens.push(branchLabel(inc.parent, inc.edge.label))
      current = inc.parent
    }
    return new Set(tokens)
  }

  const walkFind = (root: TreeNode | null, pred: (n: TreeNode) => boolean): TreeNode | null => {
    if (!root) return null
    const walk = (n: TreeNode): TreeNode | null => {
      if (pred(n)) return n
      for (const o of n.outcomes) {
        if (o.child) {
          const found = walk(o.child)
          if (found) return found
        }
      }
      return null
    }
    return walk(root)
  }

  /** Finds a node by id across BOTH trees — nodes can now live in either the
   * left or the (editable) right tree. */
  const nodeById = (id: string): TreeNode | null =>
    walkFind(state.root, (n) => n.id === id) ?? walkFind(state.rightRoot, (n) => n.id === id)

  /** The root of whichever tree owns `node` (left or right). Falls back to the
   * left root so existing left-only call sites are unaffected. Every mutation
   * routes its group-aware model call through this so it operates on the correct
   * tree, and so an edit to the right tree can be detected as a deviation. */
  const rootOf = (node: TreeNode): TreeNode => {
    if (state.rightRoot && walkFind(state.rightRoot, (n) => n === node)) return state.rightRoot
    return state.root ?? node
  }

  /** Marks the right tree as manually edited (deviated from its Bayes baseline)
   * when `node` belongs to it. Call from every right-tree mutation. */
  const touchTree = (node: TreeNode): void => {
    if (state.rightRoot && walkFind(state.rightRoot, (n) => n === node)) state.rightEdited = true
  }

  /** Same deviation check, keyed by an outcome edge (for payoff/probability
   * edits that only carry the edge, not its node). */
  const touchTreeByEdge = (edge: Outcome): void => {
    if (state.rightRoot && walkFind(state.rightRoot, (n) => n.outcomes.includes(edge))) {
      state.rightEdited = true
    }
  }

  /** After outcome(s) are added to a chance node that ALREADY has a following
   * child, extend the mirroring to the new (still-terminal) outcomes so they
   * get their own linked instance of that child variable — instead of being
   * left as leaves. E.g. a parent whose outcomes lead to nod'/nod'' gains a
   * nod''' under a newly-added outcome. Finds a template child anywhere in the
   * parent's linked group; no-op for decision parents (asymmetry is intentional)
   * or when no child exists yet. Returns the instances created. */
  const mirrorChildToNewOutcomes = (node: TreeNode): TreeNode[] => {
    if (node.nodeType !== 'chance') return []
    const owner = rootOf(node)
    let template: TreeNode | null = null
    for (const inst of [node, ...groupSiblings(owner, node)]) {
      const withChild = inst.outcomes.find((o) => o.child)
      if (withChild?.child) {
        template = withChild.child
        break
      }
    }
    if (!template) return []
    return mirrorLinkedInstances(owner, node, template, nextId)
  }

  /** Display form of a condition token "nodeId:label" -> "NodLabel = label". */
  const tokenDisplay = (token: string): string => {
    const sep = token.indexOf(':')
    const id = token.slice(0, sep)
    const label = token.slice(sep + 1)
    const node = nodeById(id)
    return `${node ? node.label : id} = ${label}`
  }

  /** Condition tokens available to `node`: only the ancestor outcomes actually
   * on this instance's path (root -> node). In a true tree each node instance
   * has exactly one path, so a condition on a *sibling* branch (e.g. "Väder =
   * Regn" for a node sitting under "Väder = Sol") can never match and would be a
   * dead row. Offering only reachable tokens keeps the conditional table honest;
   * cross-context authoring is expressed via the linked sibling instances, each
   * of which carries its own reachable path. (Legacy offered every ancestor
   * outcome because its flat-sequence nodes were shared across all paths.) */
  const availableTokens = (node: TreeNode): string[] => {
    const path: string[] = []
    for (let inc = incomingEdge(node); inc; inc = incomingEdge(inc.parent)) {
      path.push(branchLabel(inc.parent, inc.edge.label))
    }
    return path.reverse() // root-first for readable ordering
  }

  const currentDocument = (): DecisionDocument => ({
    tree: state.root,
    rightTree: state.rightRoot,
    rightEdited: state.rightEdited,
    split: state.split,
    displayMode: state.displayMode,
    utility: state.utilityFn,
    idCounter: state.idCounter,
  })

  const takeSnapshot = (): Snapshot => ({
    json: documentToJson(currentDocument()),
    selectedId: state.selected?.id ?? null,
  })

  /** Applies a deserialized document to live state (shared by restore + load). */
  const applyDocument = (doc: DecisionDocument): void => {
    state.root = doc.tree
    state.rightRoot = doc.rightTree
    state.rightEdited = doc.rightEdited
    state.split = doc.split
    state.displayMode = doc.displayMode
    state.utilityFn = doc.utility
    state.idCounter = doc.idCounter
  }

  const updateHistoryButtons = (): void => {
    undoBtn.disabled = cursor <= 0
    redoBtn.disabled = cursor >= history.length - 1
  }

  /** Records the current state as a new history entry, dropping any redo
   * future and capping the depth (oldest entries fall off silently). */
  const commitSnapshot = (): void => {
    history.length = cursor + 1 // drop the redo branch
    history.push(takeSnapshot())
    cursor++
    if (history.length > HISTORY_CAP) {
      history.shift()
      cursor--
    }
    updateHistoryButtons()
  }

  /** Establishes a fresh baseline (single entry, nothing to undo). Used at
   * startup and after loading a document — a load is a new baseline, not a
   * point in the previous document's history. */
  const resetHistory = (): void => {
    history.length = 0
    history.push(takeSnapshot())
    cursor = 0
    pendingCommit = false
    updateHistoryButtons()
  }

  const restore = (snap: Snapshot): void => {
    restoring = true
    try {
      applyDocument(deserializeDocument(snap.json))
      state.selected = snap.selectedId ? nodeById(snap.selectedId) : null
      state.dirty = true // restored state differs from the last saved file
      pendingCommit = false
      render()
    } finally {
      restoring = false
    }
    updateHistoryButtons()
  }

  const undo = (): void => {
    if (cursor <= 0) return
    cursor--
    restore(history[cursor])
  }

  const redo = (): void => {
    if (cursor >= history.length - 1) return
    cursor++
    restore(history[cursor])
  }

  /** (Re)generates the right (clairvoyance) tree from the left by Bayes
   * reversal. The left is always the source. Clears the deviation flag; on an
   * unflippable structure, stores the error and leaves no right tree. */
  const regenerateRight = (): void => {
    state.rightEdited = false
    if (!state.root) {
      state.rightRoot = null
      state.flipError = null
      return
    }
    try {
      state.rightRoot = reverseTreeWithBayes(state.root).flipped
      state.flipError = null
    } catch (e) {
      state.rightRoot = null
      state.flipError = e instanceof Error ? e.message : String(e)
    }
  }

  // ── API — every mutation goes through the model layer ──
  const api: AppApi = {
    createRoot(type, label) {
      const node = new TreeNode(nextId(), type, label)
      state.root = node
      state.selected = node
      setMessage('')
      markDirty()
      render()
      return node
    },

    addOutcomeTo(node, label, probability = NaN, value?) {
      const edge = addOutcomeToGroup(rootOf(node), node, label, probability, value)
      // If the node already has a following child, fill this new outcome with a
      // linked instance of it too (don't leave it a leaf).
      mirrorChildToNewOutcomes(node)
      touchTree(node)
      markDirty()
      render()
      return edge
    },

    attachChild(node, edge, type, label) {
      const owner = rootOf(node)
      const child = createLinkedNode(owner, nextId(), type, label)
      setChild(node, edge, child)
      state.selected = child
      touchTree(node)
      markDirty()
      // Proactively grow the same variable across the whole grid of positions
      // that should hold it: the parent's other terminal outcomes AND — when
      // the parent itself is a linked instance — the corresponding outcomes on
      // its sibling instances, all joining one linked group. Only under chance
      // parents: a chance variable recurs across its contexts, whereas decision
      // alternatives are deliberately asymmetric (act vs. don't act), so
      // auto-filling them would fight the classic decision-tree shape.
      const autoFilled =
        node.nodeType === 'chance' ? mirrorLinkedInstances(owner, node, child, nextId) : []
      if (autoFilled.length > 0) {
        const shown = [child, ...autoFilled].slice(0, 6).map((n) => `"${displayName(n)}"`).join(', ')
        const more = autoFilled.length + 1 > 6 ? ` (+${autoFilled.length + 1 - 6} till)` : ''
        setMessage(
          `Länkade instanser skapade: ${shown}${more}. ` +
            `Utfallsuppsättning, nodtyp och sannolikheter synkas automatiskt ` +
            `(en instans med egen villkorstabell styr sina egna sannolikheter).`,
        )
      } else if (child.instanceIndex > 0) {
        setMessage(
          `Länkad till variabeln "${child.label}" — utfall synkas automatiskt ` +
            `mellan alla instanser (visas som "${displayName(child)}").`,
        )
      }
      render()
      return child
    },

    toggleType(node) {
      const next = node.nodeType === 'chance' ? 'decision' : 'chance'
      // Node type is a variable-group invariant — propagate to every linked
      // instance (frikopplade instances have their own variableId, untouched).
      setNodeTypeInGroup(rootOf(node), node, next)
      touchTree(node)
      markDirty()
      render()
    },

    renameNode(node, label) {
      // Renaming propagates to the whole variable group (locked decision A).
      renameVariable(rootOf(node), node, label)
      touchTree(node)
      markDirty()
      render()
    },

    unlinkVariable(node) {
      unlinkNode(rootOf(node), node)
      touchTree(node)
      setMessage(`"${displayName(node)}" är nu frikopplad — egen variabel, synkas inte längre.`)
      markDirty()
      render()
    },

    renameOutcomeOn(node, edge, newLabel) {
      renameOutcomeInGroup(rootOf(node), node, edge, newLabel)
      touchTree(node)
      markDirty()
      render()
    },

    removeOutcomeFrom(node, edge) {
      removeOutcomeFromGroup(rootOf(node), node, edge)
      touchTree(node)
      markDirty()
      render()
    },

    reorderLevels(panelRoot, upperDepth) {
      // Rebuilds the panel's tree with the two adjacent levels swapped (throws
      // FlipError on an invalid swap — caller guards). Replaces the tree in
      // place; new node ids mean the previous selection no longer resolves.
      const restructured = reorderAdjacentLevels(panelRoot, upperDepth, nextId)
      if (panelRoot === state.rightRoot) {
        state.rightRoot = restructured
        state.rightEdited = true
      } else {
        state.root = restructured
      }
      state.selected = null
      markDirty()
      render()
    },

    setProbability(edge, probability) {
      edge.probability = probability
      touchTreeByEdge(edge)
      markDirty()
      render()
    },

    setValue(edge, value) {
      edge.value = value
      touchTreeByEdge(edge)
      markDirty()
      render()
    },

    setConditionalTable(node, rows) {
      const hadTable = node.conditionalTable.length > 0
      node.conditionalTable = rows
      const root = rootOf(node)
      touchTree(node)
      if (rows.length === 0 && hadTable) {
        // Table removed -> rejoin flat-probability sync by adopting the group's
        // shared distribution from a no-table sibling.
        adoptGroupProbabilities(root, node)
      } else if (rows.length === 0) {
        // No table before or after: base-probability edits sync to the group.
        syncProbabilitiesFromNode(root, node)
      }
      // rows.length > 0: node is now context-driven and opts out of flat sync.
      markDirty()
      render()
    },

    deleteNode(node) {
      const inRight = !!(state.rightRoot && walkFind(state.rightRoot, (n) => n === node))
      const inc = incomingEdge(node)
      if (!inc) {
        if (inRight) state.rightRoot = null
        else state.root = null
      } else {
        detachChild(inc.edge)
      }
      if (inRight) state.rightEdited = true
      if (state.selected === node) state.selected = null
      markDirty()
      render()
    },

    applyBackwardFill(node, edge, targetProbability) {
      const result = backwardFill(rootOf(node), node, edge, targetProbability)
      touchTree(node)
      const parts = result.siblings.map(
        (s) => `${s.edge.label}: ${fmt(s.oldProbability)} → ${fmt(s.newProbability)}`,
      )
      setMessage(
        `Justerade P(${displayName(result.node)} → ${result.edge.label}): ` +
          `${fmt(result.oldProbability)} → ${fmt(result.newProbability)}` +
          (parts.length > 0 ? ` · syskon omskalade: ${parts.join(', ')}` : ''),
      )
      markDirty()
      render()
    },

    exportDocument() {
      const json = documentToJson(currentDocument())
      state.dirty = false // a successful save clears the unsaved-changes flag
      return json
    },

    loadDocument(text, opts) {
      // Validate first, so a broken file never triggers a discard prompt.
      const doc = deserializeDocument(text)
      if (!opts?.skipConfirm && state.root && state.dirty) {
        if (!confirmFn('Osparade ändringar går förlorade om du laddar en fil. Fortsätt?')) {
          return false
        }
      }
      // A load restores BOTH trees exactly as saved (no regeneration) — the
      // whole point of persisting the right tree is that hand edits survive.
      applyDocument(doc)
      state.selected = null
      state.flipError = null
      state.dirty = false
      render()
      // A load is a fresh baseline — you can't undo back into the previous
      // document's history (that would produce a meaningless hybrid state).
      resetHistory()
      return true
    },

    toggleSplit() {
      if (state.split) {
        // "Sammanfoga": leave split view. The right tree is kept (persisted);
        // it will be regenerated fresh from the left the next time you flip.
        state.split = false
      } else {
        // "Flip": the LEFT tree is always the source — (re)generate the right
        // tree from it by Bayes reversal, discarding any prior manual right
        // edits (independence holds only within a split session; re-flipping
        // re-syncs from the source).
        // Drop a selection that lived in the right tree we're about to replace.
        if (state.selected && state.rightRoot && walkFind(state.rightRoot, (n) => n === state.selected)) {
          state.selected = null
        }
        regenerateRight()
        state.split = true
        state.viewRight.scale = 1
        state.viewRight.x = 0
        state.viewRight.y = 0
      }
      // Split mode is a view state, but a flip also (re)generates the right tree
      // and is a single undoable step — commit a snapshot directly.
      pendingCommit = true
      render()
    },

    undo,
    redo,
    canUndo: () => cursor > 0,
    canRedo: () => cursor < history.length - 1,

    setDisplayMode(mode) {
      state.displayMode = mode
      markDirty()
      render()
    },

    setUtilityType(type) {
      // Switching type resets the parameter to that type's sensible default;
      // the user can fine-tune afterward.
      state.utilityFn = defaultUtilityFunction(type)
      markDirty()
      render()
    },

    setUtilityParameter(parameter) {
      state.utilityFn = { ...state.utilityFn, parameter }
      markDirty()
      render()
    },

    selectNode(node) {
      state.selected = node
      render()
    },

    render,
  }

  // ── Context menu ──
  const closeMenu = (): void => {
    menuLayer.replaceChildren()
  }

  const menuItem = (label: string, onClick: () => void): HTMLButtonElement => {
    const b = document.createElement('button')
    b.type = 'button'
    b.className = 'menu-item'
    b.textContent = label
    b.addEventListener('click', () => {
      closeMenu()
      onClick()
    })
    return b
  }

  const openNodeMenu = (
    node: TreeNode,
    x: number,
    y: number,
    opts: { fromPill?: boolean } = {},
  ): void => {
    closeMenu()
    const menu = document.createElement('div')
    menu.className = 'menu'
    const rect = container.getBoundingClientRect()
    menu.style.left = `${x - rect.left}px`
    menu.style.top = `${y - rect.top}px`

    const linked = groupSiblings(rootOf(node), node).length > 0

    menu.append(
      menuItem(
        linked ? '✎ Byt namn på variabeln' : '✎ Byt namn',
        () =>
          openNameDialog(
            linked ? 'Variabelns namn (påverkar alla instanser)' : 'Nodens namn',
            node.label,
            (v) => guarded(() => api.renameNode(node, v)),
          ),
      ),
      menuItem('☰ Redigera utfall', () => openOutcomesDialog(node)),
      menuItem(
        node.nodeType === 'chance' ? '⇄ Gör till beslutsnod' : '⇄ Gör till slumpnod',
        () => guarded(() => api.toggleType(node)),
      ),
    )
    // Conditional table and Koppla loss are deliberately NOT offered from a pill
    // click — they are structural/context operations reachable only from the
    // tree itself (spec part 5).
    if (node.nodeType === 'chance' && !opts.fromPill) {
      menu.append(menuItem('⊞ Villkorstabell', () => openConditionalDialog(node)))
    }
    if (linked && !opts.fromPill) {
      menu.append(
        menuItem('⛓ Koppla loss från variabeln', () => guarded(() => api.unlinkVariable(node))),
      )
    }
    menu.append(
      menuItem('✕ Ta bort nod', () => {
        const inc = incomingEdge(node)
        const what = inc
          ? `"${displayName(node)}" och hela dess delträd tas bort — utfallet "${inc.edge.label}" blir en slutpunkt igen`
          : `Hela trädet tas bort`
        if (confirmFn(`${what}. Fortsätt?`)) guarded(() => api.deleteNode(node))
      }),
    )

    menuLayer.appendChild(menu)
  }

  container.addEventListener('click', (e) => {
    if (!(e.target as Element).closest('.menu')) closeMenu()
  })

  // ── Pill sequence bar (one per panel) ──
  // Shows each tree's ACTUAL level sequence — ONE pill per depth-level (the
  // variable at that level), with → arrows for traversal direction. Derived
  // from the live tree, never hardcoded per side. Dragging a pill onto an
  // ADJACENT pill swaps those two levels, restructuring the real tree in place
  // (api.reorderLevels). Clicking a pill opens the same edit menu as the node,
  // minus the conditional-table and Koppla-loss entries.
  interface LevelInfo {
    depth: number
    label: string
    nodeType: NodeType
    primary: TreeNode
    /** All nodes at this depth are the same variable (one variableId + type).
     * False when an unlinked/diverged instance breaks the level — such a level
     * can't be reordered past (matches the "no reorder past a bortkoppling"
     * rule); the reorder call also fails loud if attempted. */
    uniform: boolean
    /** Some node at this depth has a conditional table — a reorder wall. */
    hasTable: boolean
  }

  const levelSequence = (root: TreeNode): LevelInfo[] => {
    const byDepth: TreeNode[][] = []
    const walk = (n: TreeNode, d: number): void => {
      ;(byDepth[d] ??= []).push(n)
      for (const o of n.outcomes) if (o.child) walk(o.child, d + 1)
    }
    walk(root, 0)
    return byDepth.map((nodes, depth) => {
      const first = nodes[0]
      return {
        depth,
        label: first.label,
        nodeType: first.nodeType,
        primary: first,
        uniform: nodes.every(
          (n) => n.variableId === first.variableId && n.nodeType === first.nodeType,
        ),
        hasTable: nodes.some((n) => n.conditionalTable.length > 0),
      }
    })
  }

  let draggedLevel: { root: TreeNode; depth: number } | null = null

  const renderPillBar = (barEl: HTMLElement, root: TreeNode | null): void => {
    barEl.replaceChildren()
    if (!root) {
      barEl.style.display = 'none'
      return
    }
    barEl.style.display = ''

    const levels = levelSequence(root)
    // A level is a fixed "wall" (can't be moved / crossed) when it isn't a
    // single uniform variable or carries a conditional table.
    const locked = (lvl: LevelInfo): boolean => !lvl.uniform || lvl.hasTable

    levels.forEach((lvl, i) => {
      if (i > 0) {
        const arrow = document.createElement('span')
        arrow.className = 'pill-arrow'
        arrow.textContent = '→'
        barEl.appendChild(arrow)
      }
      const pill = document.createElement('button')
      pill.type = 'button'
      pill.className =
        `pill pill-${lvl.nodeType}` +
        (lvl.primary === state.selected ? ' selected' : '') +
        (locked(lvl) ? ' locked' : '')
      pill.textContent = lvl.label
      pill.dataset.pillDepth = String(lvl.depth)
      if (locked(lvl)) {
        pill.title = lvl.hasTable
          ? 'Har villkorstabell — låst position, kan inte ordnas om.'
          : 'Nivån är inte en enhetlig variabel (t.ex. en frikopplad instans) — kan inte ordnas om.'
      }
      pill.addEventListener('click', (e) => {
        e.stopPropagation() // else the container click-away closes the menu at once
        api.selectNode(lvl.primary)
        openNodeMenu(lvl.primary, e.clientX, e.clientY, { fromPill: true })
      })
      pill.draggable = true
      pill.addEventListener('dragstart', () => {
        draggedLevel = { root, depth: lvl.depth }
      })
      pill.addEventListener('dragover', (e) => {
        // Allow the drop only for an ADJACENT level in the SAME panel.
        if (draggedLevel && draggedLevel.root === root && Math.abs(draggedLevel.depth - lvl.depth) === 1) {
          e.preventDefault()
        }
      })
      pill.addEventListener('drop', (e) => {
        e.preventDefault()
        const dragged = draggedLevel
        draggedLevel = null
        if (!dragged || dragged.root !== root) return
        if (Math.abs(dragged.depth - lvl.depth) !== 1) return
        // Swap the two adjacent levels (upperDepth = the smaller of the two).
        guarded(() => api.reorderLevels(root, Math.min(dragged.depth, lvl.depth)))
      })
      pill.addEventListener('dragend', () => {
        draggedLevel = null
      })
      barEl.appendChild(pill)
    })
  }

  // ── Dialogs ──
  const closeDialog = (): void => {
    dialogLayer.replaceChildren()
  }

  const openDialog = (titleText: string): { body: HTMLElement; footer: HTMLElement } => {
    closeDialog()
    const overlay = document.createElement('div')
    overlay.className = 'dialog-overlay'
    const dialog = document.createElement('div')
    dialog.className = 'dialog'
    const h = document.createElement('h2')
    h.textContent = titleText
    const body = document.createElement('div')
    body.className = 'dialog-body'
    const footer = document.createElement('div')
    footer.className = 'dialog-footer'
    dialog.append(h, body, footer)
    overlay.appendChild(dialog)
    overlay.addEventListener('click', (e) => {
      if (e.target === overlay) closeDialog()
    })
    dialogLayer.appendChild(overlay)
    return { body, footer }
  }

  const dialogButton = (label: string, onClick: () => void, primary = false): HTMLButtonElement => {
    const b = document.createElement('button')
    b.type = 'button'
    b.textContent = label
    if (primary) b.className = 'primary'
    b.addEventListener('click', onClick)
    return b
  }

  const fieldRow = (labelText: string, input: HTMLElement): HTMLElement => {
    const wrap = document.createElement('label')
    wrap.className = 'field'
    const span = document.createElement('span')
    span.textContent = labelText
    wrap.append(span, input)
    return wrap
  }

  const textInput = (value: string): HTMLInputElement => {
    const input = document.createElement('input')
    input.type = 'text'
    input.value = value
    return input
  }

  const parseNum = (raw: string): number => parseFloat(raw.trim().replace(',', '.'))

  const openNameDialog = (
    titleText: string,
    initial: string,
    onOk: (value: string) => void,
  ): void => {
    const { body, footer } = openDialog(titleText)
    const input = textInput(initial)
    body.appendChild(fieldRow('Namn', input))
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' && input.value.trim()) {
        closeDialog()
        onOk(input.value.trim())
      }
    })
    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'OK',
        () => {
          if (!input.value.trim()) return
          closeDialog()
          onOk(input.value.trim())
        },
        true,
      ),
    )
    input.focus()
  }

  const openCreateRootDialog = (): void => {
    const { body, footer } = openDialog('Skapa rotnod')
    const select = document.createElement('select')
    for (const [value, text] of [
      ['chance', 'Slumpnod'],
      ['decision', 'Beslutsnod'],
    ] as const) {
      const opt = document.createElement('option')
      opt.value = value
      opt.textContent = text
      select.appendChild(opt)
    }
    const labelInput = textInput('')
    body.append(fieldRow('Typ', select), fieldRow('Namn', labelInput))
    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'Skapa',
        () => {
          const label = labelInput.value.trim()
          if (!label) return
          closeDialog()
          guarded(() => api.createRoot(select.value as NodeType, label))
        },
        true,
      ),
    )
    labelInput.focus()
  }

  /** Legacy-style outcome editor: rows of label (+ probability for chance
   * nodes), explicit Normalisera button — never silent normalization. */
  const openOutcomesDialog = (node: TreeNode): void => {
    const isChance = node.nodeType === 'chance'
    const { body, footer } = openDialog(`Utfall — ${displayName(node)}`)

    // Explain how this instance relates to its linked group. Distinguish the
    // table-driven case (probabilities here don't apply / don't sync) from the
    // plain synced case (edits propagate; a divergent value prompts a choice).
    const siblings = state.root ? groupSiblings(state.root, node) : []
    if (siblings.length > 0) {
      const note = document.createElement('p')
      note.className = 'sync-note'
      if (hasConditionalTable(node)) {
        note.textContent =
          `Den här instansen styrs av sin villkorstabell — sannolikheterna nedan ` +
          `används bara som fallback och synkas inte med gruppen (${siblings
            .map((n) => displayName(n))
            .join(', ')}). Ta bort villkorstabellen för att synka igen.`
      } else {
        note.textContent =
          `Länkad till: ${siblings.map((n) => displayName(n)).join(', ')}. ` +
          `Utfallsuppsättning och sannolikheter synkas i gruppen. Anger du andra ` +
          `sannolikheter än gruppen får du välja om det ska gälla alla eller bara den här instansen.`
      }
      body.appendChild(note)
    }

    interface Row {
      edge: Outcome | null
      labelInput: HTMLInputElement
      probInput: HTMLInputElement | null
      removed: boolean
      el: HTMLElement
    }
    const rows: Row[] = []
    const rowsHost = document.createElement('div')
    const warning = document.createElement('p')
    warning.className = 'dialog-warning'
    warning.style.display = 'none'

    const updateWarning = (): void => {
      if (!isChance) return
      let sum = 0
      let anyNaN = false
      for (const r of rows) {
        if (r.removed || !r.probInput) continue
        const v = parseNum(r.probInput.value)
        if (Number.isNaN(v)) anyNaN = true
        else sum += v
      }
      const active = rows.filter((r) => !r.removed)
      if (active.length === 0) {
        warning.style.display = 'none'
        return
      }
      if (anyNaN) {
        warning.textContent = 'p ofullständig — tomma sannolikheter visas som "–" i trädet'
        warning.style.display = ''
      } else if (Math.abs(sum - 1) > 1e-6) {
        warning.textContent = `⚠ Summan är ${fmt(sum)}, förväntat 1`
        warning.style.display = ''
      } else {
        warning.style.display = 'none'
      }
    }

    const addRow = (edge: Outcome | null): void => {
      const el = document.createElement('div')
      el.className = 'dialog-row'
      const labelInput = textInput(edge ? edge.label : '')
      labelInput.placeholder = 'etikett'
      let probInput: HTMLInputElement | null = null
      el.appendChild(labelInput)
      if (isChance) {
        probInput = textInput(edge && Number.isFinite(edge.probability) ? String(edge.probability) : '')
        probInput.placeholder = 'p'
        probInput.className = 'prob'
        probInput.addEventListener('input', updateWarning)
        el.appendChild(probInput)
      }
      const row: Row = { edge, labelInput, probInput, removed: false, el }
      el.appendChild(
        dialogButton('✕', () => {
          if (edge?.child && !confirmFn(`Utfallet "${edge.label}" har ett delträd som tas bort. Fortsätt?`)) {
            return
          }
          row.removed = true
          el.remove()
          updateWarning()
        }),
      )
      rows.push(row)
      rowsHost.appendChild(el)
    }

    for (const edge of node.outcomes) addRow(edge)
    body.append(rowsHost, warning)

    const actions = document.createElement('div')
    actions.className = 'dialog-actions'
    actions.appendChild(dialogButton('+ utfall', () => addRow(null)))
    if (isChance) {
      actions.appendChild(
        dialogButton('Normalisera', () => {
          const active = rows.filter((r) => !r.removed && r.probInput)
          if (active.length === 0) return
          const vals = active.map((r) => parseNum(r.probInput!.value))
          // Empty fields -> split evenly; otherwise scale to sum 1. Either way
          // the last outcome absorbs the rounding residual so repeating
          // decimals (thirds, sixths, …) still sum to exactly 1.
          let targets: number[]
          if (vals.some((v) => Number.isNaN(v))) {
            targets = active.map(() => 1 / active.length)
          } else {
            const sum = vals.reduce((s, v) => s + v, 0)
            if (sum <= 0) return
            targets = vals.map((v) => v / sum)
          }
          const result = distributeSumToOne(targets)
          active.forEach((r, i) => {
            r.probInput!.value = String(result[i])
          })
          updateWarning()
        }),
      )
    }
    body.appendChild(actions)
    updateWarning()

    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'Spara',
        () =>
          guarded(() => {
            const active = rows.filter((r) => !r.removed)
            const labels = active.map((r) => r.labelInput.value.trim())
            if (labels.some((l) => !l)) throw new Error('Alla utfall måste ha en etikett')
            if (new Set(labels).size !== labels.length) {
              throw new Error('Utfallsetiketter måste vara unika inom noden')
            }

            // All edits route through the group-aware model functions so the
            // outcome set stays synced across every linked instance. As of the
            // 2026-08-02 design change, probability *values* also sync across
            // the group's no-table instances (see syncProbabilitiesFromNode).
            const root = state.root ?? node
            for (const r of rows) {
              if (r.removed && r.edge) removeOutcomeFromGroup(root, node, r.edge)
            }
            for (const r of active) {
              const label = r.labelInput.value.trim()
              const prob = r.probInput ? parseNum(r.probInput.value) : NaN
              if (r.edge) {
                if (r.edge.label !== label) {
                  renameOutcomeInGroup(root, node, r.edge, label)
                }
                r.edge.probability = prob
              } else {
                addOutcomeToGroup(root, node, label, prob)
              }
            }
            // Newly-added outcomes on a chance node that already has a following
            // child get their own linked child instance too (not left as leaves).
            mirrorChildToNewOutcomes(node)
            markDirty()
            // Decide how to propagate this instance's flat probabilities. Normally
            // they sync to the group's no-table instances ("fill once"). But if the
            // user entered values that DIFFER from an already-defined group
            // distribution, silently overwriting the siblings is exactly the
            // "natural gesture fails" surprise — so we ask instead. A conditional-
            // table-driven node never syncs (opted out), and a first fill (no
            // finite donor yet) is not a divergence.
            const donor = groupSiblings(root, node).find((n) => !hasConditionalTable(n))
            const divergent =
              !hasConditionalTable(node) &&
              donor !== undefined &&
              node.outcomes.some((o) => {
                const m = donor.outcomes.find((s) => s.label === o.label)
                return (
                  m !== undefined &&
                  Number.isFinite(o.probability) &&
                  Number.isFinite(m.probability) &&
                  Math.abs(o.probability - m.probability) > 1e-9
                )
              })
            if (divergent) {
              // Leave the group untouched and defer the commit: pendingCommit
              // (set by markDirty above) survives until the choice dialog's
              // render(), so the value edit + the sync decision collapse into ONE
              // undo step. openDivergenceDialog's openDialog closes this one.
              openDivergenceDialog(node)
            } else {
              syncProbabilitiesFromNode(root, node)
              closeDialog()
              render()
            }
          }),
        true,
      ),
    )
  }

  /** Shown when a linked instance is saved with probabilities that differ from
   * its group. Lets the user choose between propagating to the whole group
   * (the "fill once" default) and giving just this instance its own values by
   * unlinking it — making the divergence explicit instead of a silent overwrite. */
  const openDivergenceDialog = (node: TreeNode): void => {
    const root = state.root ?? node
    const sibs = groupSiblings(root, node)
    const { body, footer } = openDialog('Sannolikheterna skiljer sig från gruppen')
    const p = document.createElement('p')
    p.textContent =
      `"${displayName(node)}" är länkad till ${sibs.map((n) => displayName(n)).join(', ')}. ` +
      `Du angav andra sannolikheter än gruppen. Vad vill du göra?`
    body.appendChild(p)
    footer.append(
      dialogButton('Bara den här instansen (koppla loss)', () =>
        guarded(() => {
          unlinkNode(root, node)
          setMessage(
            `"${displayName(node)}" är nu frikopplad — egen variabel med egna sannolikheter.`,
          )
          markDirty()
          closeDialog()
          render()
        }),
      ),
      dialogButton(
        'Uppdatera hela gruppen',
        () =>
          guarded(() => {
            syncProbabilitiesFromNode(root, node)
            markDirty()
            closeDialog()
            render()
          }),
        true,
      ),
    )
  }

  /** Legacy-style conditional matrix: rows = conditions, columns = the
   * node's outcomes. The base row edits the outcomes' base probabilities. */
  const openConditionalDialog = (node: TreeNode): void => {
    const { body, footer } = openDialog(`Villkorstabell — ${displayName(node)}`)
    const outcomeLabels = node.outcomes.map((o) => o.label)
    if (outcomeLabels.length === 0) {
      body.textContent = 'Noden har inga utfall än — lägg till utfall först.'
      footer.appendChild(dialogButton('Stäng', closeDialog, true))
      return
    }

    // Explain the effect a table has on linked-group sync (the "soft" opt-out).
    if (state.root && groupSiblings(state.root, node).length > 0) {
      const info = document.createElement('p')
      info.className = 'sync-note'
      info.textContent =
        'Så länge den här instansen har en villkorstabell styr den sina egna ' +
        'sannolikheter och synkas inte med gruppen. Tar du bort alla villkorsrader ' +
        'börjar den synka igen och antar gruppens fördelning.'
      body.appendChild(info)
    }

    // Show which distribution actually applies for THIS instance's path, so the
    // base row vs. a matching conditional row is never ambiguous.
    const history = historyFor(node)
    const pathTokens = availableTokens(node)
    const resolvedLine = document.createElement('p')
    resolvedLine.className = 'trace-line'
    const resolvedParts = node.outcomes.map((o) => {
      let p: string
      try {
        p = fmt(resolveProbability(node, o, history))
      } catch {
        p = '⚠'
      }
      return `${o.label} = ${p}`
    })
    const pathText = pathTokens.length > 0 ? pathTokens.map(tokenDisplay).join(', ') : 'roten'
    resolvedLine.textContent = `Gäller för den här instansen (väg: ${pathText}): ${resolvedParts.join(' · ')}`
    body.appendChild(resolvedLine)

    const table = document.createElement('table')
    table.className = 'matrix'
    const thead = document.createElement('thead')
    const headRow = document.createElement('tr')
    headRow.appendChild(document.createElement('th')).textContent = 'Villkor'
    for (const label of outcomeLabels) {
      headRow.appendChild(document.createElement('th')).textContent = label
    }
    headRow.appendChild(document.createElement('th'))
    thead.appendChild(headRow)
    table.appendChild(thead)
    const tbody = document.createElement('tbody')
    table.appendChild(tbody)

    interface MatrixRow {
      condition: Set<string> | null // null = base row
      inputs: HTMLInputElement[]
      removed: boolean
      el: HTMLTableRowElement
    }
    const matrixRows: MatrixRow[] = []

    const addMatrixRow = (condition: Set<string> | null, values: (number | undefined)[]): void => {
      const tr = document.createElement('tr')
      const condCell = document.createElement('td')
      condCell.textContent = condition
        ? [...condition].map(tokenDisplay).join(' & ')
        : '(bas)'
      if (!condition) condCell.className = 'base'
      tr.appendChild(condCell)

      const inputs: HTMLInputElement[] = []
      for (const v of values) {
        const td = document.createElement('td')
        const input = textInput(v !== undefined && Number.isFinite(v) ? String(v) : '')
        input.className = 'prob'
        inputs.push(input)
        td.appendChild(input)
        tr.appendChild(td)
      }

      const row: MatrixRow = { condition, inputs, removed: false, el: tr }
      const actionCell = document.createElement('td')
      if (condition) {
        actionCell.appendChild(
          dialogButton('✕', () => {
            row.removed = true
            tr.remove()
          }),
        )
      }
      tr.appendChild(actionCell)
      matrixRows.push(row)
      tbody.appendChild(tr)
    }

    addMatrixRow(null, node.outcomes.map((o) => o.probability))
    for (const row of node.conditionalTable) {
      addMatrixRow(new Set(row.condition), outcomeLabels.map((l) => row.probabilities[l]))
    }

    body.appendChild(table)

    // Add-condition picker: one ancestor-outcome token per new row.
    const tokens = availableTokens(node)
    const picker = document.createElement('select')
    for (const token of tokens) {
      const opt = document.createElement('option')
      opt.value = token
      opt.textContent = tokenDisplay(token)
      picker.appendChild(opt)
    }
    const pickerRow = document.createElement('div')
    pickerRow.className = 'dialog-actions'
    pickerRow.append(
      picker,
      dialogButton('+ villkor', () => {
        if (!picker.value) return
        addMatrixRow(new Set([picker.value]), outcomeLabels.map(() => undefined))
      }),
    )
    if (tokens.length === 0) {
      const hint = document.createElement('p')
      hint.className = 'hint'
      hint.textContent = 'Inga villkor tillgängliga — noden har inga förfäder med utfall.'
      body.appendChild(hint)
    } else {
      body.appendChild(pickerRow)
    }

    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'Spara',
        () =>
          guarded(() => {
            const base = matrixRows[0]
            node.outcomes.forEach((o, i) => {
              o.probability = parseNum(base.inputs[i].value)
            })
            const rows: ConditionalRow[] = []
            for (const row of matrixRows.slice(1)) {
              if (row.removed || !row.condition) continue
              const probabilities: Record<string, number> = {}
              outcomeLabels.forEach((label, i) => {
                const v = parseNum(row.inputs[i].value)
                if (!Number.isNaN(v)) probabilities[label] = v
              })
              rows.push({ condition: row.condition, probabilities })
            }
            api.setConditionalTable(node, rows)
            closeDialog()
          }),
        true,
      ),
    )
  }

  /** Terminal-outcome dialog: payoff + target joint probability (changed
   * fields only, like legacy), plus attaching a child node to grow the tree. */
  const openTerminalDialog = (node: TreeNode, edge: Outcome): void => {
    const { body, footer } = openDialog(`${displayName(node)} → ${edge.label}`)

    const valueInput = textInput(edge.value !== undefined ? String(edge.value) : '')
    valueInput.placeholder = 'osatt'
    const initialValue = valueInput.value
    body.appendChild(fieldRow('Värde (payoff)', valueInput))

    // In EU mode, show the utility transform happening at this terminal.
    if (state.displayMode === 'eu') {
      const uTrace = traceTerminalUtility(edge.value, state.utilityFn)
      const uLine = document.createElement('p')
      uLine.className = 'trace-line'
      uLine.textContent = `Nyttotransform: ${uTrace.text}`
      body.appendChild(uLine)
    }

    const jointInput = textInput('')
    jointInput.placeholder = 'mål-sannolikhet (0–1]'
    body.appendChild(fieldRow('Sätt joint probability (backward-fill)', jointInput))

    const grow = document.createElement('div')
    grow.className = 'dialog-actions'
    grow.appendChild(
      dialogButton('+ Lägg till barnnod…', () => {
        closeDialog()
        openAttachChildDialog(node, edge)
      }),
    )
    body.appendChild(grow)

    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'OK',
        () =>
          guarded(() => {
            if (valueInput.value !== initialValue) {
              const raw = valueInput.value.trim()
              if (raw === '') {
                api.setValue(edge, undefined)
              } else {
                const v = parseNum(raw)
                if (Number.isNaN(v)) throw new Error('Värdet måste vara ett tal')
                api.setValue(edge, v)
              }
            }
            const jointRaw = jointInput.value.trim()
            closeDialog()
            if (jointRaw !== '') {
              api.applyBackwardFill(node, edge, parseNum(jointRaw))
            }
          }),
        true,
      ),
    )
    valueInput.focus()
  }

  const openAttachChildDialog = (node: TreeNode, edge: Outcome): void => {
    const { body, footer } = openDialog(`Ny nod efter "${edge.label}"`)
    const select = document.createElement('select')
    for (const [value, text] of [
      ['chance', 'Slumpnod'],
      ['decision', 'Beslutsnod'],
    ] as const) {
      const opt = document.createElement('option')
      opt.value = value
      opt.textContent = text
      select.appendChild(opt)
    }
    const labelInput = textInput('')
    body.append(fieldRow('Typ', select), fieldRow('Namn', labelInput))
    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'Skapa',
        () => {
          const label = labelInput.value.trim()
          if (!label) return
          closeDialog()
          guarded(() => api.attachChild(node, edge, select.value as NodeType, label))
        },
        true,
      ),
    )
    labelInput.focus()
  }

  addBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    if (state.root === null) {
      openCreateRootDialog()
    } else {
      setMessage(
        'Trädet har redan en rot — klicka på en nod för att redigera, eller på en triangel för att bygga vidare.',
      )
    }
  })

  flipBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    api.toggleSplit()
  })

  // ── Save / load ──
  saveBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    const json = api.exportDocument()
    const blob = new Blob([json], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = documentFilename(state.root)
    a.click()
    URL.revokeObjectURL(url)
    setMessage(`Sparat som ${a.download}.`)
  })

  pngBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    const treeSvg = canvasHost.querySelector('svg') as SVGSVGElement | null
    if (!state.root || !treeSvg) {
      setMessage('Inget träd att exportera.')
      return
    }
    guarded(() => {
      const base = documentFilename(state.root).replace(/\.json$/, '')
      const exported: string[] = []
      // Left (main) tree.
      const leftName = `${base}.png`
      if (exportTreePng(treeSvg, leftName)) exported.push(leftName)
      // In split mode, the right (reversed) tree is its OWN PNG file.
      const rightSvg = rightHost.querySelector('svg') as SVGSVGElement | null
      if (state.split && state.rightRoot && rightSvg) {
        const rightName = `${base}-omvant.png`
        if (exportTreePng(rightSvg, rightName)) exported.push(rightName)
      }
      setMessage(
        exported.length > 0
          ? `Exporterade ${exported.join(' + ')} (PNG, transparent bakgrund).`
          : 'Kunde inte exportera — trädet är tomt.',
      )
    })
  })

  loadBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    fileInput.click()
  })

  fileInput.addEventListener('change', () => {
    const file = fileInput.files?.[0]
    if (!file) return
    void file
      .text()
      .then((text) => {
        fileInput.value = '' // let the same file be picked again later
        guarded(() => {
          if (api.loadDocument(text)) setMessage(`Laddade ${file.name}.`)
        })
      })
      .catch(() => {
        fileInput.value = ''
        setMessage('Kunde inte läsa filen.')
      })
  })

  // ── Display-mode toggle + utility config wiring ──
  modeBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    api.setDisplayMode(state.displayMode === 'ev' ? 'eu' : 'ev')
  })

  utilityTypeSelect.addEventListener('change', () => {
    api.setUtilityType(utilityTypeSelect.value as UtilityType)
  })

  paramInput.addEventListener('change', () => {
    const gamma = parseNum(paramInput.value)
    if (Number.isFinite(gamma)) api.setUtilityParameter(gamma)
  })

  elicitBtn.addEventListener('click', (e) => {
    e.stopPropagation()
    openElicitationDialog()
  })

  /** γ elicitation: choose a method (direct indifference question, or the
   * quick reference-amount approximation), answer it, see the resulting γ and
   * risk odds r plus example certainty equivalents, then apply. */
  const openElicitationDialog = (): void => {
    const { body, footer } = openDialog('Ställ in riskattityd (γ)')

    const method = document.createElement('select')
    for (const [value, label] of [
      ['indifference', 'Indifferens-fråga'],
      ['reference', 'Snabb approximation (referensbelopp)'],
    ] as const) {
      const opt = document.createElement('option')
      opt.value = value
      opt.textContent = label
      method.appendChild(opt)
    }
    body.appendChild(fieldRow('Metod', method))

    // Method 1 — indifference probability p.
    const pField = fieldRow(
      'Sannolikhet p: indifferent mellan 0 säkert och (p: vinn 1 / 1−p: förlora 1)',
      textInput(''),
    )
    const pInput = pField.querySelector('input') as HTMLInputElement
    pInput.placeholder = '0 < p < 1 (p = 0.5 → riskneutral)'

    // Method 2 — reference amount W.
    const wField = fieldRow('Referensbelopp W (γ ≈ 0.96 / W)', textInput(''))
    const wInput = wField.querySelector('input') as HTMLInputElement
    wInput.placeholder = 'W > 0'

    body.append(pField, wField)

    const result = document.createElement('p')
    result.className = 'elicit-result'
    body.appendChild(result)

    const preview = document.createElement('p')
    preview.className = 'elicit-preview'
    body.appendChild(preview)

    let computedGamma = state.utilityFn.parameter

    const exampleCe = (gamma: number, win: number): number => {
      const fn: UtilityFunction = { type: 'exponential', parameter: gamma }
      try {
        return applyInverseUtility(
          0.5 * applyUtility(win, fn) + 0.5 * applyUtility(0, fn),
          fn,
        )
      } catch {
        return NaN
      }
    }

    const recompute = (): void => {
      try {
        if (method.value === 'indifference') {
          computedGamma = gammaFromIndifference(parseNum(pInput.value))
        } else {
          computedGamma = gammaFromReferenceAmount(parseNum(wInput.value))
        }
        const r = riskOddsFromGamma(computedGamma)
        const attitude =
          computedGamma > 1e-9 ? 'riskavert' : computedGamma < -1e-9 ? 'risksökande' : 'riskneutral'
        result.textContent = `γ = ${fmt(computedGamma)} · riskodds r = ${fmt(r)} · ${attitude}`
        preview.textContent =
          `Exempel: en 50/50-chansning om 100 är värd CE = ${fmt(exampleCe(computedGamma, 100))}; ` +
          `om 10 → CE = ${fmt(exampleCe(computedGamma, 10))}.`
      } catch (err) {
        result.textContent = err instanceof Error ? err.message : String(err)
        preview.textContent = ''
      }
    }

    const syncMethod = (): void => {
      pField.style.display = method.value === 'indifference' ? '' : 'none'
      wField.style.display = method.value === 'reference' ? '' : 'none'
      recompute()
    }
    method.addEventListener('change', syncMethod)
    pInput.addEventListener('input', recompute)
    wInput.addEventListener('input', recompute)
    syncMethod()

    footer.append(
      dialogButton('Avbryt', closeDialog),
      dialogButton(
        'Använd γ',
        () =>
          guarded(() => {
            if (!Number.isFinite(computedGamma)) {
              throw new Error('Ange ett giltigt värde först.')
            }
            // Elicitation always produces an exponential utility.
            state.utilityFn = { type: 'exponential', parameter: computedGamma }
            markDirty()
            closeDialog()
            render()
          }),
        true,
      ),
    )
  }

  /** Reflects display-mode/utility state into the top-bar controls. Built
   * once, updated every render — no listener churn. */
  const syncModeControls = (): void => {
    modeBtn.textContent = state.displayMode === 'eu' ? 'Läge: EU/CE' : 'Läge: EV'
    utilityBar.style.display = state.displayMode === 'eu' ? '' : 'none'
    if (state.displayMode !== 'eu') {
      utilityErrorEl.style.display = 'none'
      return
    }
    utilityTypeSelect.value = state.utilityFn.type
    const isExp = state.utilityFn.type === 'exponential'
    paramLabel.style.display = isExp ? '' : 'none'
    elicitBtn.style.display = isExp ? '' : 'none'
    if (isExp) {
      if (document.activeElement !== paramInput) {
        paramInput.value = String(parseFloat(state.utilityFn.parameter.toPrecision(6)))
      }
      const r = riskOddsFromGamma(state.utilityFn.parameter)
      riskReadout.textContent = `(riskodds r = ${fmt(r)})`
    } else {
      riskReadout.textContent = ''
    }

    // Surface a utility-domain error naming the cause, without crashing render.
    if (state.root) {
      try {
        certaintyEquivalent(state.root, state.utilityFn)
        utilityErrorEl.style.display = 'none'
      } catch (e) {
        if (e instanceof UtilityDomainError) {
          utilityErrorEl.textContent = e.message
          utilityErrorEl.style.display = ''
        } else {
          utilityErrorEl.style.display = 'none'
        }
      }
    } else {
      utilityErrorEl.style.display = 'none'
    }
  }

  /** EV (or CE in EU mode) of a whole tree, or NaN if incomplete/undefined. */
  const treeValue = (root: TreeNode | null): number => {
    if (!root) return NaN
    try {
      return state.displayMode === 'eu'
        ? certaintyEquivalent(root, state.utilityFn)
        : calculateExpectedValue(root)
    } catch {
      return NaN
    }
  }

  /** Renders the right (clairvoyance) pane from `state.rightRoot`. The tree is
   * generated by the flip action (regenerateRight), NOT here — this only
   * displays it, wires the SAME editing handlers as the left tree (the right
   * tree is fully editable and independent), shows the deviation indicator once
   * it has been hand-edited, and computes VOC = |value(left) − value(right)|
   * (direction-agnostic; a free comparison once the right tree deviates). */
  const renderRightPane = (): void => {
    flipBtn.textContent = state.split ? '⇄ Sammanfoga' : '⇄ Flip'
    rightPane.style.display = state.split ? '' : 'none'
    vocBar.style.display = state.split ? '' : 'none'
    vocHint.style.display = state.split ? '' : 'none'
    if (!state.split) {
      rightHost.replaceChildren()
      svgRight = null
      return
    }

    rightDeviation.style.display = state.rightEdited ? '' : 'none'
    rightCaption.textContent = state.rightEdited
      ? 'Omvänt träd — fri jämförelse'
      : 'Omvänt träd (klarsyn) — redigerbart'

    const vocLabel = state.displayMode === 'eu' ? 'VOC (CE)' : 'VOC'
    const valLabel = state.displayMode === 'eu' ? 'CE' : 'EV'

    // Unflippable structure (from the last flip): show the reason, no tree.
    if (state.flipError) {
      rightHost.replaceChildren()
      svgRight = null
      flipErrorEl.textContent = state.flipError
      flipErrorEl.style.display = ''
      vocBar.textContent = `${vocLabel} = –`
      return
    }
    flipErrorEl.style.display = 'none'

    if (!state.rightRoot) {
      rightHost.replaceChildren()
      svgRight = null
      vocBar.textContent = state.root
        ? `${vocLabel} = –`
        : `${vocLabel} = – · bygg ett träd (Lägg till nod) för att räkna ut klarsynens värde`
      return
    }

    svgRight = renderTree(rightHost, state.rightRoot, {
      selected: state.selected,
      view: state.viewRight,
      displayMode: state.displayMode,
      utilityFn: state.utilityFn,
      mirror: true, // clairvoyance tree reads root-right, branches-left
      onNodeClick: (node, e) => {
        api.selectNode(node)
        openNodeMenu(node, e.clientX, e.clientY)
      },
      onLeafClick: (node, edge) => openTerminalDialog(node, edge),
      onBackgroundClick: () => {
        state.selected = null
        closeMenu()
        render()
      },
    })

    const left = treeValue(state.root)
    const right = treeValue(state.rightRoot)
    if (!Number.isFinite(left) || !Number.isFinite(right)) {
      vocBar.textContent = `${vocLabel} = – · fyll i alla sannolikheter och utfallsvärden`
    } else {
      vocBar.textContent =
        `${valLabel} vänster = ${fmt(left)} · ${valLabel} höger = ${fmt(right)} · ` +
        `${vocLabel} = ${fmt(Math.abs(left - right))}`
    }
  }

  /** Shows the arithmetic behind the selected node's value, live and
   * mode-aware. Hidden when nothing is selected. */
  const updateTraceBar = (): void => {
    if (!state.selected) {
      traceBar.style.display = 'none'
      return
    }
    const node = state.selected
    const trace = traceNode(node, historyFor(node), state.displayMode, state.utilityFn)
    traceBar.textContent = `Beräkning (${displayName(node)}): ${trace.text}`
    traceBar.style.display = ''
  }

  function render(): void {
    svg = renderTree(canvasHost, state.root, {
      selected: state.selected,
      view: state.view,
      displayMode: state.displayMode,
      utilityFn: state.utilityFn,
      onNodeClick: (node, e) => {
        api.selectNode(node)
        openNodeMenu(node, e.clientX, e.clientY)
      },
      onLeafClick: (node, edge) => {
        openTerminalDialog(node, edge)
      },
      onBackgroundClick: () => {
        state.selected = null
        closeMenu()
        render()
      },
    })
    syncModeControls()
    renderRightPane()
    renderPillBar(leftPillBar, state.root)
    renderPillBar(rightPillBar, state.split ? state.rightRoot : null)
    updateTraceBar()

    // Commit choke point: any committed mutation set `pendingCommit` (via
    // markDirty or toggleSplit) and finishes at exactly one render(), so the
    // whole effect — including multi-node auto-fill and linked-group sync —
    // becomes ONE history entry. Suppressed while replaying an undo/redo.
    if (pendingCommit && !restoring) {
      pendingCommit = false
      commitSnapshot()
    }
  }

  // ── Keyboard: Ctrl/Cmd+Z = undo, Ctrl/Cmd+Shift+Z (or Ctrl+Y) = redo. ──
  // Skipped entirely when a text field is being edited, so the browser's own
  // text-undo applies there instead of app-level undo.
  const isEditingText = (): boolean => {
    const el = document.activeElement as HTMLElement | null
    if (!el) return false
    const tag = el.tagName
    return tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || el.isContentEditable
  }

  const onKeyDown = (e: KeyboardEvent): void => {
    if (!(e.ctrlKey || e.metaKey)) return
    const key = e.key.toLowerCase()
    const isUndo = key === 'z' && !e.shiftKey
    const isRedo = (key === 'z' && e.shiftKey) || key === 'y'
    if (!isUndo && !isRedo) return
    if (isEditingText()) return // let the field's native undo win
    e.preventDefault()
    if (isUndo) undo()
    else redo()
  }
  document.addEventListener('keydown', onKeyDown)

  undoBtn.addEventListener('click', () => undo())
  redoBtn.addEventListener('click', () => redo())

  render()
  resetHistory() // baseline: the initial (empty) document
  return { state, api }
}
